[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# Increasing timeout helps with model loading
headless = true
maxUploadSize = 15
# Increase timeout to accommodate model loading times
deploymentMode = "development"
enableStaticServing = true
